### ISSUE TITLE
http://weather.msn.com/RSS.aspx is dead.

### ISSUE THREAD

**Issue by tsuwatch** [taiki45/weather_jp#18]
こんにちは．

`ruboty-japan_weather`を使わせて頂いていたのですが，最近になって`Error: the MSN weather sever may be downed, or got invaild city code`と出るようになりました．
少し調べましたところ，http://weather.msn.com/RSS.aspx がもう使えなくなっているみたいです．

**Comment by taiki45** [comment]
すみません、気づいてなかったです。別の方から Twitter でメンションをもらって update しました！ https://github.com/taiki45/weather_jp/pull/19

**Comment by taiki45** [comment]
Please re-open if you still has problems about this issue ;)

**Comment by tsuwatch** [comment]
ありがとうございました :)

**Comment by shokai** [comment]
:beer:
